# Generated by Django 5.1.6 on 2025-02-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
