# Generated by Django 5.1.6 on 2025-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingBank',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clothing_bank',
                'managed': False,
            },
        ),
    ]
