# Generated by Django 5.1.6 on 2025-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=45)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_user_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
